# Generated by Django 6.0.7 on 2026-07-29 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance', models.TextField(blank=True, null=True)),
                ('page', models.CharField(blank=True, default='', max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('raw_model_output', models.TextField(blank=True, null=True)),
                ('links', models.JSONField(default=list)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('model_id', models.CharField(blank=True, max_length=255)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'pk'],
            },
        ),
    ]
