# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_theme_config_palette_per_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_drawer_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
